### ISSUE TITLE
(plugin svelte) ParseError: Unexpected token

### ISSUE THREAD

**Issue by mahesh557** [nateshmbhat/svelte-ace#16]
Hi, Getting below error when trying to use ace editor.
Can you take a look and help.

```
rollup v3.21.5
bundles src/main.js → public/build/bundle.js...
[!] (plugin svelte) ParseError: Unexpected token
node_modules/svelte-ace/src/AceEditor.svelte
 7:   )}`;
 8:   const dispatch = createEventDispatcher<{
 9:     init: ace.Editor;
                        ^
10:     input: string;
11:     selectionChange: any;
    at error (D:\Workspace\Coding\WebApps\svelte-ace-editor\node_modules\svelte\src\compiler\utils\error.ts:25:16)
    at Parser$1.error (D:\Workspace\Coding\WebApps\svelte-ace-editor\node_modules\svelte\src\compiler\parse\index.ts:105:3)
    at Parser$1.acorn_error (D:\Workspace\Coding\WebApps\svelte-ace-editor\node_modules\svelte\src\compiler\parse\index.ts:98:8)
    at Object.read_script [as read] (D:\Workspace\Coding\WebApps\svelte-ace-editor\node_modules\svelte\src\compiler\parse\read\script.ts:43:10)
    at tag (D:\Workspace\Coding\WebApps\svelte-ace-editor\node_modules\svelte\src\compiler\parse\state\tag.ts:211:27)
    at new Parser$1 (D:\Workspace\Coding\WebApps\svelte-ace-editor\node_modules\svelte\src\compiler\parse\index.ts:57:12)
    at parse (D:\Workspace\Coding\WebApps\svelte-ace-editor\node_modules\svelte\src\compiler\parse\index.ts:230:17)
    at compile (D:\Workspace\Coding\WebApps\svelte-ace-editor\node_modules\svelte\src\compiler\compile\index.ts:122:14)
    at Object.transform (D:\Workspace\Coding\WebApps\svelte-ace-editor\node_modules\rollup-plugin-svelte\index.js:144:21)
    at D:\Workspace\Coding\WebApps\svelte-ace-editor\node_modules\rollup\dist\shared\rollup.js:25046:40
```

**Comment by mahesh557** [comment]
found the answer. I had to enable typescript to get it working using below command
```
 node scripts/setupTypeScript.js
 ```
